server:
  port: 8084
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?autoReconnect=true&useSSL=false
    username: user
    password: ****
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
  batch.initialize-schema: always
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    generate-ddl: true
    ddl-auto: update
